defmodule Watchman.Setup do
  @moduledoc "Interactive configuration wizard."

  @config_dir "~/.config/watchman"
  @config_path "~/.config/watchman/config.toml"

  def run do
    IO.puts("""

    ┌─────────────────────────────┐
    │     Watchman Setup          │
    └─────────────────────────────┘
    """)

    ai = choose_ai_provider()
    market = choose_market_provider()
    keys = collect_api_keys(ai, market)
    pipeline = configure_pipeline()
    storage = choose_key_storage(keys)

    store_keys(keys, storage)
    write_config(ai, market, keys, pipeline, storage)

    IO.puts("""

    Config saved to #{Path.expand(@config_path)}
    #{if storage == :keyring, do: "API keys stored in system keyring", else: "API keys stored in config file (chmod 600)"}

    Next steps:
      wm assets MXRF11 PETR4 ITUB4
      wm run
    """)
  end

  defp choose_ai_provider do
    IO.puts("""
    AI Provider
      [1] Claude (Anthropic) — web search + structured analysis
      [2] Gemini (Google) — Google Search grounding
      [3] DeepSeek — knowledge-based, no web search, cheaper
    """)

    case prompt("Choose [1-3]", "1") do
      "1" -> "claude"
      "2" -> "gemini"
      "3" -> "deepseek"
      _ -> "claude"
    end
  end

  defp choose_market_provider do
    IO.puts("""

    Market Data Provider
      [1] Brapi (brapi.dev) — Brazilian market, free tier available
      [2] Yahoo Finance — international, no API key needed
    """)

    case prompt("Choose [1-2]", "1") do
      "1" -> "brapi"
      "2" -> "yfinance"
      _ -> "brapi"
    end
  end

  defp collect_api_keys(ai, market) do
    IO.puts("\n    API Keys (press Enter to skip)\n")

    keys = %{}

    keys = case ai do
      "claude" ->
        key = prompt_secret("  Anthropic API key")
        Map.put(keys, :anthropic_key, key)
      "gemini" ->
        key = prompt_secret("  Gemini API key")
        Map.put(keys, :gemini_key, key)
      "deepseek" ->
        key = prompt_secret("  DeepSeek API key")
        Map.put(keys, :deepseek_key, key)
    end

    keys = case market do
      "brapi" ->
        key = prompt_secret("  Brapi token")
        Map.put(keys, :brapi_token, key)
      "yfinance" ->
        keys
    end

    keys
  end

  defp configure_pipeline do
    IO.puts("\n    Pipeline Settings\n")

    concurrency = prompt("  Max concurrent analyses", "10")
    timeout = prompt("  Timeout per analysis (seconds)", "120")

    %{
      max_concurrency: parse_int(concurrency, 10),
      timeout_seconds: parse_int(timeout, 120)
    }
  end

  defp choose_key_storage(keys) when map_size(keys) == 0, do: :config_file

  defp choose_key_storage(_keys) do
    if Watchman.Credentials.available?() do
      prompt_key_storage()
    else
      IO.puts("\n    System keyring not available. Using config file.\n")
      :config_file
    end
  end

  defp prompt_key_storage do
    IO.puts("""

    Key Storage
      [1] System keyring (recommended) — keys never stored as plaintext
      [2] Config file — encrypted with chmod 600
    """)

    case prompt("Choose [1-2]", "1") do
      "1" -> :keyring
      "2" -> :config_file
      _ -> :keyring
    end
  end

  defp store_keys(keys, :keyring) do
    Enum.each(keys, fn {key, value} -> store_key(key, value) end)
  end

  defp store_keys(_keys, :config_file), do: :ok

  defp store_key(_key, ""), do: :ok

  defp store_key(key, value) do
    case Watchman.Credentials.put(key, value) do
      :ok -> IO.puts("    Saved #{key} to keyring")
      {:error, reason} -> IO.puts("    Failed to save #{key}: #{inspect(reason)}")
    end
  end

  defp write_config(ai, market, keys, pipeline, storage) do
    dir = Path.expand(@config_dir)
    path = Path.expand(@config_path)

    File.mkdir_p!(dir)

    content = build_toml(ai, market, keys, pipeline, storage)
    File.write!(path, content)

    File.chmod!(path, 0o600)
  end

  defp build_toml(ai, market, keys, pipeline, storage) do
    api_section = case storage do
      :keyring ->
        """
        [api]
        # Keys stored in system keyring (managed by: wm setup)
        # To update keys, run: wm setup
        """
      :config_file ->
        """
        [api]
        # Keys stored here with chmod 600. Do NOT commit this file.
        anthropic_key = "#{Map.get(keys, :anthropic_key, "")}"
        gemini_key = "#{Map.get(keys, :gemini_key, "")}"
        deepseek_key = "#{Map.get(keys, :deepseek_key, "")}"
        brapi_token = "#{Map.get(keys, :brapi_token, "")}"
        """
    end

    """
    # Watchman configuration
    # Generated by: wm setup

    #{api_section}
    [providers]
    ai = "#{ai}"
    market = "#{market}"

    [pipeline]
    max_concurrency = #{pipeline.max_concurrency}
    timeout_seconds = #{pipeline.timeout_seconds}
    """
  end

  # Helpers

  defp prompt(label, default) do
    result = IO.gets("  #{label} [#{default}]: ") |> String.trim()
    if result == "", do: default, else: result
  end

  defp prompt_secret(label) do
    IO.write("#{label}: ")
    :io.get_password() |> to_string() |> String.trim()
  end

  defp parse_int(str, default) do
    case Integer.parse(str) do
      {n, _} -> n
      :error -> default
    end
  end
end
